<?php
declare(strict_types=1);
class CasoController extends Controller {
    public function index(): void { $this->view('casos/index',['casos'=>(new Caso())->list()]); }
    public function create(): void { require_role(['ADMINISTRADOR','EVALUADOR']); $s=new Sustancia(); $this->view('casos/create',['sustancias'=>$s->active(),'unidades'=>$s->unidades(),'vias'=>$s->vias(),'normativas'=>(new Normativa())->active()]); }
    public function store(): void { require_role(['ADMINISTRADOR','EVALUADOR']); verify_csrf(); try { $codigo='RAD-'.date('Ymd').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6)); $nombres=post_text('nombres',150); $edad=post_int('edad',0,120); $sexo=post_enum('sexo',['MASCULINO','FEMENINO','NO_ESPECIFICA']); $ocupacion=post_text('ocupacion',120,false); $vulnerable=post_enum('condicion_vulnerable',['NINGUNA','NIÑO','GESTANTE','ADULTO_MAYOR','TRABAJADOR_EXPUSTO','OTRA']); $antecedentes=post_text('antecedentes',2000,false); $sid=post_int('sustancia_id',1,999999); $nid=post_int('normativa_id',1,999999); $uidUnidad=post_int('unidad_id',1,999999); $vid=post_int('via_id',1,999999); $tipo_evento=post_enum('tipo_evento',['LABORAL','AMBIENTAL','INDUSTRIAL','MEDICO','DOMESTICO','DESCONOCIDO']); $fecha=post_text('fecha_exposicion',30); $ts=strtotime($fecha); if(!$ts || $ts > time()+3600) throw new RuntimeException('La fecha de exposición es inválida o futura.'); $fechaSql=date('Y-m-d H:i:s',$ts); $lugar=post_text('lugar_evento',180); $tiempo=post_float('tiempo_exposicion_horas',0.01,100000); $valor=post_float('valor_medido',0,999999999); $tipo_muestra=post_enum('tipo_muestra',['SANGRE','ORINA','CABELLO','AGUA','AIRE','SUELO','MEDICION_RADIOLOGICA','OTRA']); $sintomas=post_text('sintomas',2500); $zona=post_text('zona_corporal',120,false); $equipo=post_text('equipo_utilizado',160,false);
        $sm=new Sustancia(); $sustancia=$sm->find($sid); if(!$sustancia) throw new RuntimeException('Sustancia no válida.'); if(!(new Normativa())->existsActive($nid)) throw new RuntimeException('Normativa no válida.'); if(!$sm->unidadOk($sid,$uidUnidad)) throw new RuntimeException('La unidad no corresponde a la sustancia seleccionada.'); if(!$sm->viaOk($sid,$vid)) throw new RuntimeException('La vía no corresponde a la sustancia seleccionada.'); if($tipo_muestra==='MEDICION_RADIOLOGICA' && $sustancia['tipo']!=='RADIACTIVA') throw new RuntimeException('Una medición radiológica solo corresponde a sustancias radiactivas.'); $escala=(new EscalaRiesgo())->match($sid,$nid,$uidUnidad,$valor); if(!$escala) throw new RuntimeException('No existe una escala activa para la sustancia, normativa, unidad y valor ingresados.'); $nivel=$escala['nivel']; $interpretacion='Resultado orientativo de tamizaje: '.$nivel.'. '.$escala['accion']; if($vulnerable!=='NINGUNA') $interpretacion.=' Condición vulnerable registrada: requiere criterio profesional.'; $estado=in_array($nivel,['MODERADO','ALTO','CRITICO'],true)?'ALERTA_GENERADA':'REGISTRADO'; $user=(int)$_SESSION['user']['id']; $caseId=(new Caso())->createWithPerson(['codigo'=>$codigo,'nombres'=>$nombres,'edad'=>$edad,'sexo'=>$sexo,'ocupacion'=>$ocupacion,'vulnerable'=>$vulnerable,'antecedentes'=>$antecedentes,'uid'=>$user],['sustancia_id'=>$sid,'normativa_id'=>$nid,'unidad_id'=>$uidUnidad,'via_id'=>$vid,'tipo_evento'=>$tipo_evento,'fecha_exposicion'=>$fechaSql,'lugar_evento'=>$lugar,'tiempo'=>$tiempo,'valor'=>$valor,'tipo_muestra'=>$tipo_muestra,'sintomas'=>$sintomas,'zona'=>$zona,'equipo'=>$equipo,'nivel'=>$nivel,'interpretacion'=>$interpretacion,'estado'=>$estado]); audit_log('CREAR_CASO','casos',$caseId,'Nivel: '.$nivel.' / Sustancia: '.$sustancia['nombre']); flash('success','Caso registrado y clasificado como '.$nivel.'.'); redirect(url('caso','show',['id'=>$caseId])); } catch(Throwable $e){ flash('danger',$e->getMessage()); redirect(url('caso','create')); } }
    public function show(): void { $id=(int)($_GET['id']??0); $c=(new Caso())->findDetail($id); if(!$c){ flash('danger','Caso no encontrado.'); redirect(url('caso')); } $this->view('casos/show',['c'=>$c]); }
    public function review(): void { require_role(['ADMINISTRADOR','ESPECIALISTA']); verify_csrf(); $id=post_int('caso_id',1,999999999); $estado=post_enum('estado',['EN_REVISION','DERIVADO','CERRADO']); $obs=post_text('observacion_especialista',2500); (new Caso())->review($id,$estado,$obs,(int)$_SESSION['user']['id']); audit_log('REVISAR_CASO','casos',$id,$estado); flash('success','Caso actualizado por especialista.'); redirect(url('caso','show',['id'=>$id])); }
}
