<?php
declare(strict_types=1);
class Caso extends Model {
    public function stats(): array { return ['casos'=>$this->one('SELECT COUNT(*) total FROM casos')['total']??0, 'alertas'=>$this->one('SELECT COUNT(*) total FROM alertas WHERE estado="PENDIENTE"')['total']??0, 'alto'=>$this->one('SELECT COUNT(*) total FROM casos WHERE nivel_riesgo IN ("ALTO","CRITICO")')['total']??0, 'sustancias'=>$this->one('SELECT COUNT(*) total FROM sustancias WHERE estado="ACTIVO"')['total']??0]; }
    public function riesgos(): array { return $this->all('SELECT nivel_riesgo, COUNT(*) total FROM casos GROUP BY nivel_riesgo ORDER BY FIELD(nivel_riesgo,"BAJO","MODERADO","ALTO","CRITICO","NO_CLASIFICADO")'); }
    public function ultimos(int $limit=8): array { return $this->all('SELECT c.id,p.codigo,p.nombres,s.nombre sustancia,c.nivel_riesgo,c.estado,c.created_at FROM casos c JOIN personas p ON p.id=c.persona_id JOIN sustancias s ON s.id=c.sustancia_id ORDER BY c.id DESC LIMIT '.$limit); }
    public function list(): array { return $this->all('SELECT c.id,p.codigo,p.nombres,s.nombre sustancia,u.simbolo,c.valor_medido,c.nivel_riesgo,c.estado,c.created_at FROM casos c JOIN personas p ON p.id=c.persona_id JOIN sustancias s ON s.id=c.sustancia_id JOIN unidades u ON u.id=c.unidad_id ORDER BY c.id DESC LIMIT 100'); }
    public function findDetail(int $id): ?array { return $this->one('SELECT c.*,p.codigo,p.nombres,p.edad,p.sexo,p.ocupacion,p.condicion_vulnerable,p.antecedentes,s.nombre sustancia,s.tipo,n.nombre normativa,u.simbolo,v.nombre via,cr.nombre creador FROM casos c JOIN personas p ON p.id=c.persona_id JOIN sustancias s ON s.id=c.sustancia_id JOIN normativas n ON n.id=c.normativa_id JOIN unidades u ON u.id=c.unidad_id JOIN vias_exposicion v ON v.id=c.via_id JOIN usuarios cr ON cr.id=c.created_by WHERE c.id=?','i',[$id]); }
    public function createWithPerson(array $p, array $c): int { $this->db->begin_transaction(); try { $stmtP=$this->db->prepare('INSERT INTO personas(codigo,nombres,edad,sexo,ocupacion,condicion_vulnerable,antecedentes,created_by) VALUES(?,?,?,?,?,?,?,?)'); $stmtP->bind_param('ssissssi',$p['codigo'],$p['nombres'],$p['edad'],$p['sexo'],$p['ocupacion'],$p['vulnerable'],$p['antecedentes'],$p['uid']); $stmtP->execute(); $persona_id=(int)$this->db->insert_id; $stmtC=$this->db->prepare('INSERT INTO casos(persona_id,sustancia_id,normativa_id,unidad_id,via_id,tipo_evento,fecha_exposicion,lugar_evento,tiempo_exposicion_horas,valor_medido,tipo_muestra,sintomas,zona_corporal,equipo_utilizado,nivel_riesgo,interpretacion,estado,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'); $stmtC->bind_param('iiiiisssddsssssssi',$persona_id,$c['sustancia_id'],$c['normativa_id'],$c['unidad_id'],$c['via_id'],$c['tipo_evento'],$c['fecha_exposicion'],$c['lugar_evento'],$c['tiempo'],$c['valor'],$c['tipo_muestra'],$c['sintomas'],$c['zona'],$c['equipo'],$c['nivel'],$c['interpretacion'],$c['estado'],$p['uid']); $stmtC->execute(); $caseId=(int)$this->db->insert_id; if($c['estado']==='ALERTA_GENERADA'){ (new Alerta())->create($caseId,$c['nivel'],'Caso con riesgo '.$c['nivel'].'. Requiere revisión por perfil competente.'); } $this->db->commit(); return $caseId; } catch(Throwable $e){ $this->db->rollback(); throw $e; } }
    public function review(int $id,string $estado,string $obs,int $uid): void { $stmt=$this->db->prepare('UPDATE casos SET estado=?, reviewed_by=?, observacion_especialista=? WHERE id=?'); $stmt->bind_param('sisi',$estado,$uid,$obs,$id); $stmt->execute(); }
}
